version: '3.3'
services:
  semantic-service:
    build: .
    container_name: "semantic-api"
    ports:
      - "15400:15400"
    deploy:
      resources:
        limits:
          memory: 200M
    volumes:
      - ./app/:/app
